export const REGISTRATION_PATH = '/registration'
export const LOGIN_PATH = '/login'
export const LOGOUT_PATH = '/logout'
export const ACTIVATE_PATH = '/activate/:link'
export const REFRESH_PATH = '/refresh'
export const USERS_PATH = '/users'
export const USERS_PATH_BY_ID = '/users/:id'
export const TEST_PATH = '/alive'
export const MAX_AGE_REFRESH_TOKEN=30*24*60*60*1000// 30*24*60*60*1000 30 days //30 days //30*1000 - 30sec
